services:
  app:
    image: movie-crud-app
    container_name: books-library-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      APP_NAME: "Books Library"
      APP_ENV: local
      APP_KEY: ${APP_KEY}
      APP_DEBUG: true
      APP_URL: http://listapelis.com/api
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: books_library
      DB_USERNAME: root
      DB_PASSWORD: secret
    networks:
      - books-network
      - web-proxy

  web:
    image: nginx:alpine
    container_name: books-library-nginx
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - books-network
      - web-proxy

  db:
    image: mariadb:10.6
    container_name: books-library-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: books_library
    volumes:
      - books-db-data:/var/lib/mysql
    networks:
      - books-network

networks:
  books-network:
    driver: bridge
  web-proxy:
    external: true

volumes:
  books-db-data:
